# Generated by Django 3.0.8 on 2020-08-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos_api', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
